# export_instagram_cookies.py
import browser_cookie3

cj = browser_cookie3.chrome(domain_name='instagram.com')

with open('cookies.txt', 'w') as f:
    f.write("# Netscape HTTP Cookie File\n")
    f.write("# This file was generated by browser-cookie3\n")
    f.write("# https://curl.se/docs/http-cookies.html\n\n")
    for cookie in cj:
        # domain, flag, path, secure, expiration, name, value
        f.write(
            f"{cookie.domain}\t"
            f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
            f"{cookie.path}\t"
            f"{'TRUE' if cookie.secure else 'FALSE'}\t"
            f"{int(cookie.expires) if cookie.expires else 0}\t"
            f"{cookie.name}\t"
            f"{cookie.value}\n"
        )
print("cookies.txt exported!")
# This script exports Instagram cookies from Chrome to a cookies.txt file.